# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mbta_client.models.active_period import ActivePeriod
from mbta_client.models.informed_entity import InformedEntity
from typing import Optional, Set
from typing_extensions import Self

class AlertResourceAttributes(BaseModel):
    """
    AlertResourceAttributes
    """ # noqa: E501
    url: Optional[StrictStr] = Field(default=None, description="A URL for extra details, such as outline construction or maintenance plans.")
    updated_at: Optional[datetime] = Field(default=None, description="Date/Time alert last updated. Format is ISO8601.")
    timeframe: Optional[StrictStr] = Field(default=None, description="Summarizes when an alert is in effect.")
    short_header: Optional[StrictStr] = Field(default=None, description="A shortened version of `*/attributes/header`.")
    severity: Optional[Annotated[int, Field(le=10, strict=True, ge=0)]] = Field(default=None, description="How severe the alert is from least (`0`) to most (`10`) severe.")
    service_effect: Optional[StrictStr] = Field(default=None, description="Summarizes the service and the impact to that service.")
    lifecycle: Optional[StrictStr] = Field(default=None, description="Identifies whether alert is a new or old, in effect or upcoming.  | Value                | |----------------------| | `\"NEW\"`              | | `\"ONGOING\"`          | | `\"ONGOING_UPCOMING\"` | | `\"UPCOMING\"`         |  ")
    informed_entity: Optional[List[InformedEntity]] = Field(default=None, description="Entities affected by this alert.")
    image_alternative_text: Optional[StrictStr] = Field(default=None, description="Text describing the appearance of the linked image in the image field.")
    image: Optional[StrictStr] = Field(default=None, description="URL of an image to be displayed alongside alert.")
    header: Optional[StrictStr] = Field(default=None, description="This plain-text string will be highlighted, for example in boldface. See [GTFS Realtime `FeedMessage` `FeedEntity` `Alert` `header_text`](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-alert) ")
    effect_name: Optional[StrictStr] = Field(default=None, description="Name of the alert")
    effect: Optional[StrictStr] = Field(default=None, description="The effect of this problem on the affected entity.  | Value | |-------| | `\"ACCESS_ISSUE\"` | | `\"ADDITIONAL_SERVICE\"` | | `\"AMBER_ALERT\"` | | `\"BIKE_ISSUE\"` | | `\"CANCELLATION\"` | | `\"DELAY\"` | | `\"DETOUR\"` | | `\"DOCK_CLOSURE\"` | | `\"DOCK_ISSUE\"` | | `\"ELEVATOR_CLOSURE\"` | | `\"ESCALATOR_CLOSURE\"` | | `\"EXTRA_SERVICE\"` | | `\"FACILITY_ISSUE\"` | | `\"MODIFIED_SERVICE\"` | | `\"NO_SERVICE\"` | | `\"OTHER_EFFECT\"` | | `\"PARKING_CLOSURE\"` | | `\"PARKING_ISSUE\"` | | `\"POLICY_CHANGE\"` | | `\"SCHEDULE_CHANGE\"` | | `\"SERVICE_CHANGE\"` | | `\"SHUTTLE\"` | | `\"SNOW_ROUTE\"` | | `\"STATION_CLOSURE\"` | | `\"STATION_ISSUE\"` | | `\"STOP_CLOSURE\"` | | `\"STOP_MOVE\"` | | `\"STOP_MOVED\"` | | `\"SUMMARY\"` | | `\"SUSPENSION\"` | | `\"TRACK_CHANGE\"` | | `\"UNKNOWN_EFFECT\"` |  See [GTFS Realtime `FeedMessage` `FeedEntity` `Alert` `effect`](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-alert)  ")
    duration_certainty: Optional[StrictStr] = Field(default=None, description="| Value | |-------| | `\"UNKNOWN\"` | | `\"KNOWN\"` | | `\"ESTIMATED\"` | Indicates whether an alert has a KNOWN, ESTIMATED, or UNKNOWN duration. KNOWN duration_certainty alerts are expected to end at the specified end time, ESTIMATED duration_certainty alerts have an estimated end time, and UNKNOWN duration_certainty alerts do not have a known or estimated end time.  ")
    description: Optional[StrictStr] = Field(default=None, description="This plain-text string will be formatted as the body of the alert (or shown on an explicit \"expand\" request by the user). The information in the description should add to the information of the header. See [GTFS Realtime `FeedMessage` `FeedEntity` `Alert` `description_text`](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-alert) ")
    created_at: Optional[datetime] = Field(default=None, description="Date/Time alert created. Format is ISO8601.")
    cause: Optional[StrictStr] = Field(default=None, description="What is causing the alert.  | Value | |-------| | `\"ACCIDENT\"` | | `\"AMTRAK_TRAIN_TRAFFIC\"` | | `\"COAST_GUARD_RESTRICTION\"` | | `\"CONSTRUCTION\"` | | `\"CROSSING_ISSUE\"` | | `\"DEMONSTRATION\"` | | `\"DISABLED_BUS\"` | | `\"DISABLED_TRAIN\"` | | `\"DRAWBRIDGE_BEING_RAISED\"` | | `\"ELECTRICAL_WORK\"` | | `\"FIRE\"` | | `\"FIRE_DEPARTMENT_ACTIVITY\"` | | `\"FLOODING\"` | | `\"FOG\"` | | `\"FREIGHT_TRAIN_INTERFERENCE\"` | | `\"HAZMAT_CONDITION\"` | | `\"HEAVY_RIDERSHIP\"` | | `\"HIGH_WINDS\"` | | `\"HOLIDAY\"` | | `\"HURRICANE\"` | | `\"ICE_IN_HARBOR\"` | | `\"MAINTENANCE\"` | | `\"MECHANICAL_ISSUE\"` | | `\"MECHANICAL_PROBLEM\"` | | `\"MEDICAL_EMERGENCY\"` | | `\"PARADE\"` | | `\"POLICE_ACTION\"` | | `\"POLICE_ACTIVITY\"` | | `\"POWER_PROBLEM\"` | | `\"RAIL_DEFECT\"` | | `\"SEVERE_WEATHER\"` | | `\"SIGNAL_ISSUE\"` | | `\"SIGNAL_PROBLEM\"` | | `\"SINGLE_TRACKING\"` | | `\"SLIPPERY_RAIL\"` | | `\"SNOW\"` | | `\"SPECIAL_EVENT\"` | | `\"SPEED_RESTRICTION\"` | | `\"SWITCH_ISSUE\"` | | `\"SWITCH_PROBLEM\"` | | `\"TIE_REPLACEMENT\"` | | `\"TRACK_PROBLEM\"` | | `\"TRACK_WORK\"` | | `\"TRAFFIC\"` | | `\"TRAIN_TRAFFIC\"` | | `\"UNRULY_PASSENGER\"` | | `\"WEATHER\"` |  See [GTFS Realtime `FeedMessage` `FeedEntity` `Alert` `Cause`](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-cause)  ")
    banner: Optional[StrictStr] = Field(default=None, description="Set if alert is meant to be displayed prominently, such as the top of every page.")
    active_period: Optional[List[ActivePeriod]] = Field(default=None, description="Date/Time ranges when alert is active. See [GTFS Realtime `FeedMessage` `FeedEntity` `Alert` `active_period`](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-alert). ")
    __properties: ClassVar[List[str]] = ["url", "updated_at", "timeframe", "short_header", "severity", "service_effect", "lifecycle", "informed_entity", "image_alternative_text", "image", "header", "effect_name", "effect", "duration_certainty", "description", "created_at", "cause", "banner", "active_period"]

    @field_validator('effect')
    def effect_validate_enum(cls, value):
        return value

    @field_validator('duration_certainty')
    def duration_certainty_validate_enum(cls, value):
        return value

    @field_validator('cause')
    def cause_validate_enum(cls, value):
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in informed_entity (list)
        _items = []
        if self.informed_entity:
            for _item_informed_entity in self.informed_entity:
                if _item_informed_entity:
                    _items.append(_item_informed_entity.to_dict())
            _dict['informed_entity'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in active_period (list)
        _items = []
        if self.active_period:
            for _item_active_period in self.active_period:
                if _item_active_period:
                    _items.append(_item_active_period.to_dict())
            _dict['active_period'] = _items
        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if timeframe (nullable) is None
        # and model_fields_set contains the field
        if self.timeframe is None and "timeframe" in self.model_fields_set:
            _dict['timeframe'] = None

        # set to None if image_alternative_text (nullable) is None
        # and model_fields_set contains the field
        if self.image_alternative_text is None and "image_alternative_text" in self.model_fields_set:
            _dict['image_alternative_text'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if banner (nullable) is None
        # and model_fields_set contains the field
        if self.banner is None and "banner" in self.model_fields_set:
            _dict['banner'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "updated_at": obj.get("updated_at"),
            "timeframe": obj.get("timeframe"),
            "short_header": obj.get("short_header"),
            "severity": obj.get("severity"),
            "service_effect": obj.get("service_effect"),
            "lifecycle": obj.get("lifecycle"),
            "informed_entity": [InformedEntity.from_dict(_item) for _item in obj["informed_entity"]] if obj.get("informed_entity") is not None else None,
            "image_alternative_text": obj.get("image_alternative_text"),
            "image": obj.get("image"),
            "header": obj.get("header"),
            "effect_name": obj.get("effect_name"),
            "effect": obj.get("effect"),
            "duration_certainty": obj.get("duration_certainty"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "cause": obj.get("cause"),
            "banner": obj.get("banner"),
            "active_period": [ActivePeriod.from_dict(_item) for _item in obj["active_period"]] if obj.get("active_period") is not None else None
        })
        return _obj


