# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from mbta_client.models.route_resource_relationships_route_patterns_data_inner import RouteResourceRelationshipsRoutePatternsDataInner
from mbta_client.models.route_resource_relationships_route_patterns_links import RouteResourceRelationshipsRoutePatternsLinks
from typing import Optional, Set
from typing_extensions import Self

class RouteResourceRelationshipsRoutePatterns(BaseModel):
    """
    RouteResourceRelationshipsRoutePatterns
    """ # noqa: E501
    links: Optional[RouteResourceRelationshipsRoutePatternsLinks] = None
    data: Optional[List[RouteResourceRelationshipsRoutePatternsDataInner]] = None
    __properties: ClassVar[List[str]] = ["links", "data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouteResourceRelationshipsRoutePatterns from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouteResourceRelationshipsRoutePatterns from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "links": RouteResourceRelationshipsRoutePatternsLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "data": [RouteResourceRelationshipsRoutePatternsDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None
        })
        return _obj


