# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from mbta_client.models.route_resource_relationships_agency import RouteResourceRelationshipsAgency
from mbta_client.models.route_resource_relationships_line import RouteResourceRelationshipsLine
from mbta_client.models.route_resource_relationships_route_patterns import RouteResourceRelationshipsRoutePatterns
from typing import Optional, Set
from typing_extensions import Self

class RouteResourceRelationships(BaseModel):
    """
    RouteResourceRelationships
    """ # noqa: E501
    route_patterns: Optional[RouteResourceRelationshipsRoutePatterns] = None
    line: Optional[RouteResourceRelationshipsLine] = None
    agency: Optional[RouteResourceRelationshipsAgency] = None
    __properties: ClassVar[List[str]] = ["route_patterns", "line", "agency"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouteResourceRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of route_patterns
        if self.route_patterns:
            _dict['route_patterns'] = self.route_patterns.to_dict()
        # override the default output from pydantic by calling `to_dict()` of line
        if self.line:
            _dict['line'] = self.line.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agency
        if self.agency:
            _dict['agency'] = self.agency.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouteResourceRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "route_patterns": RouteResourceRelationshipsRoutePatterns.from_dict(obj["route_patterns"]) if obj.get("route_patterns") is not None else None,
            "line": RouteResourceRelationshipsLine.from_dict(obj["line"]) if obj.get("line") is not None else None,
            "agency": RouteResourceRelationshipsAgency.from_dict(obj["agency"]) if obj.get("agency") is not None else None
        })
        return _obj


