# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RouteResourceAttributes(BaseModel):
    """
    RouteResourceAttributes
    """ # noqa: E501
    type: Optional[StrictInt] = Field(default=None, description="| Value | Name          | Example    | |-------|---------------|------------| | `0`   | Light Rail    | Green Line | | `1`   | Heavy Rail    | Red Line   | | `2`   | Commuter Rail |            | | `3`   | Bus           |            | | `4`   | Ferry         |            | ")
    text_color: Optional[StrictStr] = Field(default=None, description="A legible color to use for text drawn against a background of the route's `color` attribute. See [GTFS `routes.txt` `route_text_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt). ")
    sort_order: Optional[StrictInt] = Field(default=None, description="Routes sort in ascending order")
    short_name: Optional[StrictStr] = Field(default=None, description="This will often be a short, abstract identifier like \"32\", \"100X\", or \"Green\" that riders use to identify a route, but which doesn't give any indication of what places the route serves. See [GTFS `routes.txt` `route_short_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt). ")
    long_name: Optional[StrictStr] = Field(default=None, description="The full name of a route. This name is generally more descriptive than the `short_name` and will often include the route's destination or stop. See [GTFS `routes.txt` `route_long_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt). ")
    fare_class: Optional[StrictStr] = Field(default=None, description="Specifies the fare type of the route, which can differ from the service category. ")
    direction_names: Optional[List[Optional[StrictStr]]] = None
    direction_destinations: Optional[List[Optional[StrictStr]]] = None
    description: Optional[StrictStr] = Field(default=None, description="Details about stops, schedule, and/or service.  See [GTFS `routes.txt` `route_desc`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt). ")
    color: Optional[StrictStr] = Field(default=None, description="A color that corresponds to the route, such as the line color on a map.\" See [GTFS `routes.txt` `route_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt). ")
    __properties: ClassVar[List[str]] = ["type", "text_color", "sort_order", "short_name", "long_name", "fare_class", "direction_names", "direction_destinations", "description", "color"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouteResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouteResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "text_color": obj.get("text_color"),
            "sort_order": obj.get("sort_order"),
            "short_name": obj.get("short_name"),
            "long_name": obj.get("long_name"),
            "fare_class": obj.get("fare_class"),
            "direction_names": obj.get("direction_names"),
            "direction_destinations": obj.get("direction_destinations"),
            "description": obj.get("description"),
            "color": obj.get("color")
        })
        return _obj


