# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ServiceResourceAttributes(BaseModel):
    """
    ServiceResourceAttributes
    """ # noqa: E501
    valid_days: Optional[List[Union[StrictFloat, StrictInt]]] = None
    start_date: Optional[date] = Field(default=None, description="Earliest date which is valid for this service. Format is ISO8601.")
    schedule_typicality: Optional[StrictInt] = Field(default=None, description="Describes how well this schedule represents typical service for the listed `schedule_type`  | Value | Description                                                                 | |-------|-----------------------------------------------------------------------------| | `0`   | Not defined.                                                                | | `1`   | Typical service with perhaps minor modifications                            | | `2`   | Extra service supplements typical schedules                                 | | `3`   | Reduced holiday service is provided by typical Saturday or Sunday schedule  | | `4`   | Major changes in service due to a planned disruption, such as construction  | | `5`   | Major reductions in service for weather events or other atypical situations | | `6`   | Canonical service contains default stopping patterns for selected routes, including temporarily closed stops; not active on any dates | ")
    schedule_type: Optional[StrictStr] = Field(default=None, description="Description of the schedule type the service_id can be applied. For example, on a holiday, the schedule_type value may be \"Saturday\" or \"Sunday\". Current valid values are \"Weekday\", \"Saturday\", \"Sunday\", or \"Other\" ")
    schedule_name: Optional[StrictStr] = Field(default=None, description="Description of when the `service_id` is in effect.")
    removed_dates_notes: Optional[List[StrictStr]] = None
    removed_dates: Optional[List[date]] = None
    rating_start_date: Optional[date] = Field(default=None, description="Earliest date which is a part of the rating (season) which contains this service. Format is ISO8601.")
    rating_end_date: Optional[date] = Field(default=None, description="Latest date which is a part of the rating (season) which contains this service. Format is ISO8601.")
    rating_description: Optional[StrictStr] = Field(default=None, description="Human-readable description of the rating (season), as it should appear on public-facing websites and applications.")
    end_date: Optional[date] = Field(default=None, description="Latest date which is valid for this service. Format is ISO8601.")
    description: Optional[StrictStr] = Field(default=None, description="Human-readable description of the service, as it should appear on public-facing websites and applications.")
    added_dates_notes: Optional[List[StrictStr]] = None
    added_dates: Optional[List[date]] = None
    __properties: ClassVar[List[str]] = ["valid_days", "start_date", "schedule_typicality", "schedule_type", "schedule_name", "removed_dates_notes", "removed_dates", "rating_start_date", "rating_end_date", "rating_description", "end_date", "description", "added_dates_notes", "added_dates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if schedule_type (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_type is None and "schedule_type" in self.model_fields_set:
            _dict['schedule_type'] = None

        # set to None if schedule_name (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_name is None and "schedule_name" in self.model_fields_set:
            _dict['schedule_name'] = None

        # set to None if rating_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.rating_start_date is None and "rating_start_date" in self.model_fields_set:
            _dict['rating_start_date'] = None

        # set to None if rating_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.rating_end_date is None and "rating_end_date" in self.model_fields_set:
            _dict['rating_end_date'] = None

        # set to None if rating_description (nullable) is None
        # and model_fields_set contains the field
        if self.rating_description is None and "rating_description" in self.model_fields_set:
            _dict['rating_description'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "valid_days": obj.get("valid_days"),
            "start_date": obj.get("start_date"),
            "schedule_typicality": obj.get("schedule_typicality"),
            "schedule_type": obj.get("schedule_type"),
            "schedule_name": obj.get("schedule_name"),
            "removed_dates_notes": obj.get("removed_dates_notes"),
            "removed_dates": obj.get("removed_dates"),
            "rating_start_date": obj.get("rating_start_date"),
            "rating_end_date": obj.get("rating_end_date"),
            "rating_description": obj.get("rating_description"),
            "end_date": obj.get("end_date"),
            "description": obj.get("description"),
            "added_dates_notes": obj.get("added_dates_notes"),
            "added_dates": obj.get("added_dates")
        })
        return _obj


