# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class StopResourceAttributes(BaseModel):
    """
    StopResourceAttributes
    """ # noqa: E501
    wheelchair_boarding: Optional[StrictInt] = Field(default=None, description="Whether there are any vehicles with wheelchair boarding or paths to stops that are wheelchair acessible: 0, 1, 2.  Wheelchair boarding (`*/attributes/wheelchair_boarding`) corresponds to [GTFS wheelchair_boarding](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). The MBTA handles parent station inheritance itself, so value can be treated simply:  | Value | Meaning                                       | |-------|-----------------------------------------------| | `0`   | No Information                                | | `1`   | Accessible (if trip is wheelchair accessible) | | `2`   | Inaccessible                                  |  ")
    vehicle_type: Optional[StrictInt] = Field(default=None, description="The type of transportation used at the stop. `vehicle_type` will be a valid routes.txt `route_type` value:  | Value | Name          | Example    | |-------|---------------|------------| | `0`   | Light Rail    | Green Line | | `1`   | Heavy Rail    | Red Line   | | `2`   | Commuter Rail |            | | `3`   | Bus           |            | | `4`   | Ferry         |            |  ")
    platform_name: Optional[StrictStr] = Field(default=None, description="A textual description of the platform or track. See [MBTA extensions to GTFS](https://docs.google.com/document/d/1RoQQj3_-7FkUlzFP4RcK1GzqyHp4An2lTFtcmW0wrqw/view). ")
    platform_code: Optional[StrictStr] = Field(default=None, description="A short code representing the platform/track (like a number or letter). See [GTFS `stops.txt` `platform_code`](https://developers.google.com/transit/gtfs/reference/gtfs-extensions#stopstxt_1). ")
    on_street: Optional[StrictStr] = Field(default=None, description="The street on which the stop is located.")
    name: Optional[StrictStr] = Field(default=None, description="Name of a stop or station in the local and tourist vernacular.  See [GTFS `stops.txt` `stop_name](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt) ")
    municipality: Optional[StrictStr] = Field(default=None, description="The municipality in which the stop is located.")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the stop or station. Degrees East, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#Longitudes_on_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lon`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). ")
    location_type: Optional[StrictInt] = Field(default=None, description="The type of the stop.  | Value | Type | Description | | - | - | - | | `0` | Stop | A location where passengers board or disembark from a transit vehicle. | | `1` | Station | A physical structure or area that contains one or more stops. | | `2` | Station Entrance/Exit | A location where passengers can enter or exit a station from the street. The stop entry must also specify a parent_station value referencing the stop ID of the parent station for the entrance. | | `3` | Generic Node | A location within a station, not matching any other location_type, which can be used to link together pathways defined in pathways.txt. |  See also [GTFS `stops.txt` `location_type`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). ")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the stop or station.  Degrees North, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lat`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). ")
    description: Optional[StrictStr] = Field(default=None, description="Description of the stop. See [GTFS `stops.txt` `stop_desc`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). ")
    at_street: Optional[StrictStr] = Field(default=None, description="The cross street at which the stop is located.")
    address: Optional[StrictStr] = Field(default=None, description="A street address for the station. See [MBTA extensions to GTFS](https://docs.google.com/document/d/1RoQQj3_-7FkUlzFP4RcK1GzqyHp4An2lTFtcmW0wrqw/view). ")
    __properties: ClassVar[List[str]] = ["wheelchair_boarding", "vehicle_type", "platform_name", "platform_code", "on_street", "name", "municipality", "longitude", "location_type", "latitude", "description", "at_street", "address"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StopResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if vehicle_type (nullable) is None
        # and model_fields_set contains the field
        if self.vehicle_type is None and "vehicle_type" in self.model_fields_set:
            _dict['vehicle_type'] = None

        # set to None if platform_name (nullable) is None
        # and model_fields_set contains the field
        if self.platform_name is None and "platform_name" in self.model_fields_set:
            _dict['platform_name'] = None

        # set to None if platform_code (nullable) is None
        # and model_fields_set contains the field
        if self.platform_code is None and "platform_code" in self.model_fields_set:
            _dict['platform_code'] = None

        # set to None if on_street (nullable) is None
        # and model_fields_set contains the field
        if self.on_street is None and "on_street" in self.model_fields_set:
            _dict['on_street'] = None

        # set to None if municipality (nullable) is None
        # and model_fields_set contains the field
        if self.municipality is None and "municipality" in self.model_fields_set:
            _dict['municipality'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if at_street (nullable) is None
        # and model_fields_set contains the field
        if self.at_street is None and "at_street" in self.model_fields_set:
            _dict['at_street'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StopResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wheelchair_boarding": obj.get("wheelchair_boarding"),
            "vehicle_type": obj.get("vehicle_type"),
            "platform_name": obj.get("platform_name"),
            "platform_code": obj.get("platform_code"),
            "on_street": obj.get("on_street"),
            "name": obj.get("name"),
            "municipality": obj.get("municipality"),
            "longitude": obj.get("longitude"),
            "location_type": obj.get("location_type"),
            "latitude": obj.get("latitude"),
            "description": obj.get("description"),
            "at_street": obj.get("at_street"),
            "address": obj.get("address")
        })
        return _obj


