# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from mbta_client.models.schedule_resource_relationships_route import ScheduleResourceRelationshipsRoute
from mbta_client.models.trip_resource_relationships_occupancy import TripResourceRelationshipsOccupancy
from mbta_client.models.trip_resource_relationships_route_pattern import TripResourceRelationshipsRoutePattern
from mbta_client.models.trip_resource_relationships_service import TripResourceRelationshipsService
from mbta_client.models.trip_resource_relationships_shape import TripResourceRelationshipsShape
from typing import Optional, Set
from typing_extensions import Self

class TripResourceRelationships(BaseModel):
    """
    TripResourceRelationships
    """ # noqa: E501
    shape: Optional[TripResourceRelationshipsShape] = None
    service: Optional[TripResourceRelationshipsService] = None
    route_pattern: Optional[TripResourceRelationshipsRoutePattern] = None
    route: Optional[ScheduleResourceRelationshipsRoute] = None
    occupancy: Optional[TripResourceRelationshipsOccupancy] = None
    __properties: ClassVar[List[str]] = ["shape", "service", "route_pattern", "route", "occupancy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TripResourceRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of shape
        if self.shape:
            _dict['shape'] = self.shape.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        # override the default output from pydantic by calling `to_dict()` of route_pattern
        if self.route_pattern:
            _dict['route_pattern'] = self.route_pattern.to_dict()
        # override the default output from pydantic by calling `to_dict()` of route
        if self.route:
            _dict['route'] = self.route.to_dict()
        # override the default output from pydantic by calling `to_dict()` of occupancy
        if self.occupancy:
            _dict['occupancy'] = self.occupancy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TripResourceRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "shape": TripResourceRelationshipsShape.from_dict(obj["shape"]) if obj.get("shape") is not None else None,
            "service": TripResourceRelationshipsService.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "route_pattern": TripResourceRelationshipsRoutePattern.from_dict(obj["route_pattern"]) if obj.get("route_pattern") is not None else None,
            "route": ScheduleResourceRelationshipsRoute.from_dict(obj["route"]) if obj.get("route") is not None else None,
            "occupancy": TripResourceRelationshipsOccupancy.from_dict(obj["occupancy"]) if obj.get("occupancy") is not None else None
        })
        return _obj


