# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TripResourceAttributes(BaseModel):
    """
    TripResourceAttributes
    """ # noqa: E501
    wheelchair_accessible: Optional[StrictInt] = Field(default=None, description="Indicator of wheelchair accessibility: `0`, `1`, `2`  Wheelchair accessibility (`*/attributes/wheelchair_accessible`) [as defined in GTFS](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#tripstxt):  | Value | Meaning                                            | |-------|----------------------------------------------------| | `0`   | No information                                     | | `1`   | Accessible (at stops allowing wheelchair_boarding) | | `2`   | Inaccessible                                       |  ")
    revenue_status: Optional[StrictStr] = Field(default=None, description="| Value           | Description | |-----------------|-------------| | `\"REVENUE\"`     | Indicates that the associated trip is accepting passengers. | | `\"NON_REVENUE\"` | Indicates that the associated trip is not accepting passengers. | ")
    name: Optional[StrictStr] = Field(default=None, description="The text that appears in schedules and sign boards to identify the trip to passengers, for example, to identify train numbers for commuter rail trips. See [GTFS `trips.txt` `trip_short_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#tripstxt) ")
    headsign: Optional[StrictStr] = Field(default=None, description="The text that appears on a sign that identifies the trip's destination to passengers. See [GTFS `trips.txt` `trip_headsign`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#tripstxt). ")
    direction_id: Optional[StrictInt] = Field(default=None, description="Direction in which trip is traveling: `0` or `1`.  The meaning of `direction_id` varies based on the route. You can programmatically get the direction names from `/routes` `/data/{index}/attributes/direction_names` or `/routes/{id}` `/data/attributes/direction_names`.  ")
    block_id: Optional[StrictStr] = Field(default=None, description="ID used to group sequential trips with the same vehicle for a given service_id. See [GTFS `trips.txt` `block_id`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#tripstxt) ")
    bikes_allowed: Optional[StrictInt] = Field(default=None, description="Indicator of whether or not bikes are allowed on this trip: `0`, `1`, `2`  Bikes allowed (`*/attributes/bikes_allowed`) [as defined in GTFS](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#tripstxt):  | Value | Meaning                                                                         | |-------|---------------------------------------------------------------------------------| | `0`   | No information                                                                  | | `1`   | Vehicle being used on this particular trip can accommodate at least one bicycle | | `2`   | No bicycles are allowed on this trip                                            |  ")
    __properties: ClassVar[List[str]] = ["wheelchair_accessible", "revenue_status", "name", "headsign", "direction_id", "block_id", "bikes_allowed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TripResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TripResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wheelchair_accessible": obj.get("wheelchair_accessible"),
            "revenue_status": obj.get("revenue_status"),
            "name": obj.get("name"),
            "headsign": obj.get("headsign"),
            "direction_id": obj.get("direction_id"),
            "block_id": obj.get("block_id"),
            "bikes_allowed": obj.get("bikes_allowed")
        })
        return _obj


