# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from mbta_client.models.vehicle_resource_attributes_carriages_inner import VehicleResourceAttributesCarriagesInner
from typing import Optional, Set
from typing_extensions import Self

class VehicleResourceAttributes(BaseModel):
    """
    VehicleResourceAttributes
    """ # noqa: E501
    updated_at: Optional[datetime] = Field(default=None, description="Time at which vehicle information was last updated. Format is ISO8601.")
    speed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Speed that the vehicle is traveling in meters per second. See [GTFS-realtime Position speed](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-position).")
    revenue_status: Optional[StrictStr] = Field(default=None, description="| Value           | Description | |-----------------|-------------| | `\"REVENUE\"`     | Indicates that the associated trip is accepting passengers. | | `\"NON_REVENUE\"` | Indicates that the associated trip is not accepting passengers. | ")
    occupancy_status: Optional[StrictStr] = Field(default=None, description="The degree of passenger occupancy for the vehicle. See [GTFS-realtime OccupancyStatus](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-vehiclestopstatus).  | _**Value**_                    | _**Description**_                                                                                   | |--------------------------------|-----------------------------------------------------------------------------------------------------| | **MANY_SEATS_AVAILABLE**       | Not crowded: the vehicle has a large percentage of seats available. | | **FEW_SEATS_AVAILABLE**        | Some crowding: the vehicle has a small percentage of seats available. | | **STANDING_ROOM_ONLY**         | Standing room only: the vehicle can currently accommodate only standing passengers. | | **CRUSHED_STANDING_ROOM_ONLY** | Crushed standing room: the vehicle can currently accommodate only standing passengers and has limited space for them. | | **FULL**                       | Crowded: the vehicle is considered full by most measures, but may still be allowing passengers to board. | | **NOT_ACCEPTING_PASSENGERS**   | Not accepting passengers: the vehicle is not accepting passengers, the vehicle or carriage usually accepts passengers for boarding. | | **NO_DATA_AVAILABLE**          | No data available: the vehicle doesn't have any occupancy data available at that time. |  ")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the vehicle's current position.  Degrees East, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#Longitudes_on_WGS.C2.A084) coordinate system. See [GTFS-realtime Position longitude](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-position).")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the vehicle's current position. Degrees North, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS.C2.A084) coordinate system. See [GTFS-realtime Position latitude](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-position).")
    label: Optional[StrictStr] = Field(default=None, description="User visible label, such as the one of on the signage on the vehicle.  See [GTFS-realtime VehicleDescriptor label](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-vehicledescriptor).")
    direction_id: Optional[StrictInt] = Field(default=None, description="Direction in which trip is traveling: `0` or `1`.  The meaning of `direction_id` varies based on the route. You can programmatically get the direction names from `/routes` `/data/{index}/attributes/direction_names` or `/routes/{id}` `/data/attributes/direction_names`.  ")
    current_stop_sequence: Optional[StrictInt] = Field(default=None, description="Index of current stop along trip. See [GTFS-realtime VehiclePosition current_stop_sequence](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-vehicleposition)")
    current_status: Optional[StrictStr] = Field(default=None, description="Status of vehicle relative to the stops. See [GTFS-realtime VehicleStopStatus](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#enum-vehiclestopstatus).  | _**Value**_       | _**Description**_                                                                                          | |-------------------|------------------------------------------------------------------------------------------------------------| | **INCOMING_AT**   | The vehicle is just about to arrive at the stop (on a stop display, the vehicle symbol typically flashes). | | **STOPPED_AT**    | The vehicle is standing at the stop.                                                                       | | **IN_TRANSIT_TO** | The vehicle has departed the previous stop and is in transit.                                              |  ")
    carriages: Optional[List[VehicleResourceAttributesCarriagesInner]] = Field(default=None, description="Carriage-level crowding details. See [GTFS-realtime multi_carriage_details](https://gtfs.org/documentation/realtime/reference/#message-carriagedetails). ")
    bearing: Optional[StrictInt] = Field(default=None, description="Bearing, in degrees, clockwise from True North, i.e., 0 is North and 90 is East. This can be the compass bearing, or the direction towards the next stop or intermediate location. See [GTFS-realtime Position bearing](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-position).")
    __properties: ClassVar[List[str]] = ["updated_at", "speed", "revenue_status", "occupancy_status", "longitude", "latitude", "label", "direction_id", "current_stop_sequence", "current_status", "carriages", "bearing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VehicleResourceAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in carriages (list)
        _items = []
        if self.carriages:
            for _item_carriages in self.carriages:
                if _item_carriages:
                    _items.append(_item_carriages.to_dict())
            _dict['carriages'] = _items
        # set to None if occupancy_status (nullable) is None
        # and model_fields_set contains the field
        if self.occupancy_status is None and "occupancy_status" in self.model_fields_set:
            _dict['occupancy_status'] = None

        # set to None if carriages (nullable) is None
        # and model_fields_set contains the field
        if self.carriages is None and "carriages" in self.model_fields_set:
            _dict['carriages'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VehicleResourceAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "updated_at": obj.get("updated_at"),
            "speed": obj.get("speed"),
            "revenue_status": obj.get("revenue_status"),
            "occupancy_status": obj.get("occupancy_status"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude"),
            "label": obj.get("label"),
            "direction_id": obj.get("direction_id"),
            "current_stop_sequence": obj.get("current_stop_sequence"),
            "current_status": obj.get("current_status"),
            "carriages": [VehicleResourceAttributesCarriagesInner.from_dict(_item) for _item in obj["carriages"]] if obj.get("carriages") is not None else None,
            "bearing": obj.get("bearing")
        })
        return _obj


